<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Subcategory;

class SubcategoriesTableSeeder extends Seeder
{
    public function run()
    {
        \App\Models\User::factory(50)->create();
        // Subcategories for INC Insurance
        Subcategory::create([
            'subcategory_id' => 1,
            'name' => 'Auto Insurance',
            'route' => 'auto_insurance',
            'tags' => 'insurance, auto',
            'moto' => 'Affortable inc out there',
            'qoute1' => 'Affordable Coverage',
            'qoute2' => 'Peace of Mind',
            'qoute3' => 'Customizable Plans',
            'qoute4' => 'Multi-Policy Discounts',
            'qoute5' => 'Emergency Assistance',
            'description' => 'Our auto insurance offers affordable coverages to protect you and your ride through the road ahead. Get an auto insurance quote today to stay protected when you drive. Make sure you feel safe on the road wherever you go. Our auto insurance covers injuries and damages so that you can drive feeling assured en route to your next destination.',
            'benefits' => 'Insurance With PrimeOne Comes excellence.',
            'description2' => 'Choosing our auto insurance means more than just coverage – it means safeguarding your journey with confidence. Heres how you benefit',
            'price' => '150',
        ]);
        Subcategory::create([
                'subcategory_id' => 1,
                'name' => 'Home insurance',
                'route' => 'home_insurance',
                'tags' => 'insurance, ',
                'moto' => 'Safe inc out there',
                'qoute1' => 'Affordable Coverage',
                'qoute2' => 'Peace of Mind',
                'qoute3' => 'Customizable Plans',
                'qoute4' => 'Multi-Policy Discounts',
                'qoute5' => 'Emergency Assistance',
                'description' => 'Our auto insurance offers affordable coverages to protect you and your ride through the road ahead. Get an auto insurance quote today to stay protected when you drive. Make sure you feel safe on the road wherever you go. Our auto insurance covers injuries and damages so that you can drive feeling assured en route to your next destination.',
                'benefits' => 'Insurance With PrimeOne Comes excellence.',
                'description2' => 'Choosing our Renters insurance means more than just coverage – it means safeguarding your journey with confidence. Heres how you benefit',
                'price' => '100',
            ]);
            Subcategory::create([
                'subcategory_id' => 1,
                'name' => 'Business insurance',
                'route' => 'business_insurance',
                'tags' => 'insurance, Business',
                'moto' => 'Safe inc out there',
                'qoute1' => 'Affordable Coverage',
                'qoute2' => 'Peace of Mind',
                'qoute3' => 'Customizable Plans',
                'qoute4' => 'Multi-Policy Discounts',
                'qoute5' => 'Emergency Assistance',
                'description' => 'Our auto insurance offers affordable coverages to protect you and your ride through the road ahead. Get an auto insurance quote today to stay protected when you drive. Make sure you feel safe on the road wherever you go. Our auto insurance covers injuries and damages so that you can drive feeling assured en route to your next destination.',
                'benefits' => 'Insurance With PrimeOne Comes excellence.',
                'description2' => 'Choosing our Renters insurance means more than just coverage – it means safeguarding your journey with confidence. Heres how you benefit',
                'price' => '100',
            ]);
            Subcategory::create([
                'subcategory_id' => 1,
                'name' => 'Life insurance',
                'route' => 'life_insurance',
                'tags' => 'insurance, Life',
                'moto' => 'Safe inc out there',
                'qoute1' => 'Affordable Coverage',
                'qoute2' => 'Peace of Mind',
                'qoute3' => 'Customizable Plans',
                'qoute4' => 'Multi-Policy Discounts',
                'qoute5' => 'Emergency Assistance',
                'description' => 'Our auto insurance offers affordable coverages to protect you and your ride through the road ahead. Get an auto insurance quote today to stay protected when you drive. Make sure you feel safe on the road wherever you go. Our auto insurance covers injuries and damages so that you can drive feeling assured en route to your next destination.',
                'benefits' => 'Insurance With PrimeOne Comes excellence.',
                'description2' => 'Choosing our Renters insurance means more than just coverage – it means safeguarding your journey with confidence. Heres how you benefit',
                'price' => '100',
            ]);
            Subcategory::create([
                'subcategory_id' => 1,
                'name' => 'Motorcycle insurance',
                'route' => 'motorcycle_insurance',
                'tags' => 'insurance, Motorcycle',
                'moto' => 'Safe inc out there',
                'qoute1' => 'Affordable Coverage',
                'qoute2' => 'Peace of Mind',
                'qoute3' => 'Customizable Plans',
                'qoute4' => 'Multi-Policy Discounts',
                'qoute5' => 'Emergency Assistance',
                'description' => 'Our auto insurance offers affordable coverages to protect you and your ride through the road ahead. Get an auto insurance quote today to stay protected when you drive. Make sure you feel safe on the road wherever you go. Our auto insurance covers injuries and damages so that you can drive feeling assured en route to your next destination.',
                'benefits' => 'Insurance With PrimeOne Comes excellence.',
                'description2' => 'Choosing our Renters insurance means more than just coverage – it means safeguarding your journey with confidence. Heres how you benefit',
                'price' => '100',
            ]);
            Subcategory::create([
                'subcategory_id' => 1,
                'name' => 'Recreational insurance',
                'route' => 'recreational_insurance',
                'tags' => 'insurance, Recreational',
                'moto' => 'Safe inc out there',
                'qoute1' => 'Affordable Coverage',
                'qoute2' => 'Peace of Mind',
                'qoute3' => 'Customizable Plans',
                'qoute4' => 'Multi-Policy Discounts',
                'qoute5' => 'Emergency Assistance',
                'description' => 'Our auto insurance offers affordable coverages to protect you and your ride through the road ahead. Get an auto insurance quote today to stay protected when you drive. Make sure you feel safe on the road wherever you go. Our auto insurance covers injuries and damages so that you can drive feeling assured en route to your next destination.',
                'benefits' => 'Insurance With PrimeOne Comes excellence.',
                'description2' => 'Choosing our Renters insurance means more than just coverage – it means safeguarding your journey with confidence. Heres how you benefit',
                'price' => '100',
            ]);
            Subcategory::create([
                'subcategory_id' => 1,
                'name' => 'Umbrella insurance',
                'route' => 'umbrella_insurance',
                'tags' => 'insurance, Umbrella',
                'moto' => 'Safe inc out there',
                'qoute1' => 'Affordable Coverage',
                'qoute2' => 'Peace of Mind',
                'qoute3' => 'Customizable Plans',
                'qoute4' => 'Multi-Policy Discounts',
                'qoute5' => 'Emergency Assistance',
                'description' => 'Our auto insurance offers affordable coverages to protect you and your ride through the road ahead. Get an auto insurance quote today to stay protected when you drive. Make sure you feel safe on the road wherever you go. Our auto insurance covers injuries and damages so that you can drive feeling assured en route to your next destination.',
                'benefits' => 'Insurance With PrimeOne Comes excellence.',
                'description2' => 'Choosing our Renters insurance means more than just coverage – it means safeguarding your journey with confidence. Heres how you benefit',
                'price' => '100',
            ]);
            Subcategory::create([
                'subcategory_id' => 1,
                'name' => 'Disability insurance',
                'route' => 'disability_insurance',
                'tags' => 'insurance, Disability',
                'moto' => 'Safe inc out there',
                'qoute1' => 'Affordable Coverage',
                'qoute2' => 'Peace of Mind',
                'qoute3' => 'Customizable Plans',
                'qoute4' => 'Multi-Policy Discounts',
                'qoute5' => 'Emergency Assistance',
                'description' => 'Our auto insurance offers affordable coverages to protect you and your ride through the road ahead. Get an auto insurance quote today to stay protected when you drive. Make sure you feel safe on the road wherever you go. Our auto insurance covers injuries and damages so that you can drive feeling assured en route to your next destination.',
                'benefits' => 'Insurance With PrimeOne Comes excellence.',
                'description2' => 'Choosing our Renters insurance means more than just coverage – it means safeguarding your journey with confidence. Heres how you benefit',
                'price' => '100',
            ]);
            Subcategory::create([
                'subcategory_id' => 1,
                'name' => 'Renters Insurance',
                'route' => 'renters_insurance',
                'tags' => 'insurance, Renters',
                'moto' => 'Safe inc out there',
                'qoute1' => 'Affordable Coverage',
                'qoute2' => 'Peace of Mind',
                'qoute3' => 'Customizable Plans',
                'qoute4' => 'Multi-Policy Discounts',
                'qoute5' => 'Emergency Assistance',
                'description' => 'Our auto insurance offers affordable coverages to protect you and your ride through the road ahead. Get an auto insurance quote today to stay protected when you drive. Make sure you feel safe on the road wherever you go. Our auto insurance covers injuries and damages so that you can drive feeling assured en route to your next destination.',
                'benefits' => 'Insurance With PrimeOne Comes excellence.',
                'description2' => 'Choosing our Renters insurance means more than just coverage – it means safeguarding your journey with confidence. Heres how you benefit',
                'price' => '100',
            ]);
            Subcategory::create([
                'subcategory_id' => 1,
                'name' => 'Liability insurance',
                'route' => 'liability_insurance',
                'tags' => 'insurance, Liability',
                'moto' => 'Safe inc out there',
                'qoute1' => 'Affordable Coverage',
                'qoute2' => 'Peace of Mind',
                'qoute3' => 'Customizable Plans',
                'qoute4' => 'Multi-Policy Discounts',
                'qoute5' => 'Emergency Assistance',
                'description' => 'Our auto insurance offers affordable coverages to protect you and your ride through the road ahead. Get an auto insurance quote today to stay protected when you drive. Make sure you feel safe on the road wherever you go. Our auto insurance covers injuries and damages so that you can drive feeling assured en route to your next destination.',
                'benefits' => 'Insurance With PrimeOne Comes excellence.',
                'description2' => 'Choosing our Renters insurance means more than just coverage – it means safeguarding your journey with confidence. Heres how you benefit',
                'price' => '100',
            ]);
            // TLC Services Subcategories
            Subcategory::create([
                'subcategory_id' => 2,
                'name' => 'Black Cab Insurance',
                'route' => 'blackcab_insurance',
                'tags' => 'insurance, blackcab',
                'moto' => 'Affortable inc out there',
                'qoute1' => 'Affordable Coverage',
                'qoute2' => 'Peace of Mind',
                'qoute3' => 'Customizable Plans',
                'qoute4' => 'Multi-Policy Discounts',
                'qoute5' => 'Emergency Assistance',
                'description' => 'Our auto insurance offers affordable coverages to protect you and your ride through the road ahead. Get an auto insurance quote today to stay protected when you drive. Make sure you feel safe on the road wherever you go. Our auto insurance covers injuries and damages so that you can drive feeling assured en route to your next destination.',
                'benefits' => 'Insurance With PrimeOne Comes excellence.',
                'description2' => 'Choosing our auto insurance means more than just coverage – it means safeguarding your journey with confidence. Heres how you benefit',
                'price' => '150',
            ]);
            Subcategory::create([
                'subcategory_id' => 2,
                'name' => 'Yellow Cab Insurance',
                'route' => 'yellow_insurance',
                'tags' => 'insurance, yellowcab',
                'moto' => 'Affortable inc out there',
                'qoute1' => 'Affordable Coverage',
                'qoute2' => 'Peace of Mind',
                'qoute3' => 'Customizable Plans',
                'qoute4' => 'Multi-Policy Discounts',
                'qoute5' => 'Emergency Assistance',
                'description' => 'Our auto insurance offers affordable coverages to protect you and your ride through the road ahead. Get an auto insurance quote today to stay protected when you drive. Make sure you feel safe on the road wherever you go. Our auto insurance covers injuries and damages so that you can drive feeling assured en route to your next destination.',
                'benefits' => 'Insurance With PrimeOne Comes excellence.',
                'description2' => 'Choosing our auto insurance means more than just coverage – it means safeguarding your journey with confidence. Heres how you benefit',
                'price' => '150',
            ]);
            Subcategory::create([
                'subcategory_id' => 2,
                'name' => 'Green Cab insurance',
                'route' => 'greencab_insurance',
                'tags' => 'insurance, greencab',
                'moto' => 'Safe inc out there',
                'qoute1' => 'Affordable Coverage',
                'qoute2' => 'Peace of Mind',
                'qoute3' => 'Customizable Plans',
                'qoute4' => 'Multi-Policy Discounts',
                'qoute5' => 'Emergency Assistance',
                'description' => 'Our auto insurance offers affordable coverages to protect you and your ride through the road ahead. Get an auto insurance quote today to stay protected when you drive. Make sure you feel safe on the road wherever you go. Our auto insurance covers injuries and damages so that you can drive feeling assured en route to your next destination.',
                'benefits' => 'Insurance With PrimeOne Comes excellence.',
                'description2' => 'Choosing our Renters insurance means more than just coverage – it means safeguarding your journey with confidence. Heres how you benefit',
                'price' => '100',
            ]);
    }
}